# Generated by Django 3.2.13 on 2022-05-13 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20220513_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.shipment'),
        ),
    ]
